version: 2
formats: all
build:
  apt_packages:
  - build-essential
  - libclang-dev
  - libfreefare-dev
python:
  install:
  - requirements: docs/requirements.txt
  - path: .
sphinx:
  configuration: docs/conf.py
