version: 2
formats: all
build:
  os: ubuntu-20.04
  tools:
    python: 3
  apt_packages:
  - libclang-dev
  - libfreefare-dev
python:
  install:
  - requirements: docs/requirements.txt
  - path: .
sphinx:
  configuration: docs/conf.py
