dist: xenial
language: python
python:
- '2.7'
- '3.7'
before_install:
- sudo apt-get -qq update
- sudo apt install -y libssl-dev libnfc-dev libfreefare-dev libclang-5.0-dev
script: python setup.py build test
deploy:
  provider: pypi
  user: BarnabyShearer
  skip_cleanup: true
  skip_existing: true
  distributions: "sdist bdist_wheel"
  password:
    secure: tQTxxnKhMk0yV3yf5PuhpoN8qHfMTBlN7B60ej1kkHFrf9F4f7yrDQ7vvgZOFnk2wTogv3LVvxtlVJYBMM8/Ww9Nu691wGAES4ctIevu55qYO1PS4mOZb4JokM+VioBaLiMcBKw+zxpKOJlieDKo8bVGGrCdcYvSVdRR0liBL2XaTVLo8JeAFQj8F+KIjFL0Ay68GO6Ma7ynyuSVRLtwH9KxLYA9Ab712Q6C4BwCq3N6tcY2FyRfM4t80o0+8czNLpb4XWlma4gZbtXZoI6Vrb+0u6U+GmiSTdCnrrNxt0+PXfc/Mrhlx4/gG+JmlAuHtHvEyvRcOe4CVp0/ANJDX5/VQrx8DGESMMVyKVvSRyUCo8INyLmNqq4OhmSUhCzqofpFzxYuhhj4L1WHtSsfikedBkkHB3b6XHIdbFD38Hf1HL0P3JQcD3VGzBXLjuXcVTdv+n2RcAWVZWtQNGH+3B/Ll204XGgZBwD8pgeV9fNeC0gtM2PzbIkWF/APp0WN6h3EOriHscJauimTjygwuLrSrrmXm887H4avuoc2DZyRUmgZm/a+/fwk+smPiPtoTzIwXJdt5a2vvJm4wfEeh/sJyITcE5XEXFroqGuy3jDJqM2sc51yEsbRwsE+Ue7XXOX8aNXsySLPv0EWvNTPBBap2V6ZZ0Des22yOXbw1+4=
  on:
    tags: true
